### ISSUE TITLE
The extension exited instantly. Please check the logs.

### ISSUE THREAD

**Issue by yuunam97** [zakuciael/ulauncher-wiki-search#1]
After installing cachetools (after typing pip3 install cachetools --user) in the terminal for the wiki search, it states that "The extension exited instantly. Please check the logs."

**Comment by zakuciael** [comment]
Hi, which version of python are you using?
Also, can you launch `ulauncher` from the terminal with the `-v` flag, and paste the logs here for me to examine?

**Comment by yuunam97** [comment]
Hey there :) I am using python version 3.8.

However, I found the issue. I haven't installed the required packages. That solved the problem. Apologies for the concern. 

Have a nice day further
