### ISSUE TITLE
Keyword clashes with existing Ulauncher "wiki" shortcut

### ISSUE THREAD

**Issue by justresisting** [zakuciael/ulauncher-wiki-search#3]
Installed `ulauncher-wiki-search` without realizing there was native functionality for wikipedia searches. The extension did nothing except open up wikipedia. It was Ulaunchers native wiki search being used. 

My advice would be to change this extension keyword from `wiki` to `wikisearch` or `wik`. I nearly deleted the extension before realizing Ulauncher's built in Wikipedia functionality was competing with this extension. 

Another suggesting.. I would love to use this feature to search other wiki's for data. Witcher isn't my thing but there must be tons of other wikis to choose from. I have no idea where to search for wikis. 

Perhaps you could include search features that would help users find more wikis to search from?

That would be great. I could see myself using this extension often if that were to happen.

**Comment by zakuciael** [comment]
Hi there.

I could not find the **native Wikipedia search** functionality you are describing but nonetheless
If you want to change the extension keyword, you can do this by doing this:
1. Go to the `Extensions` tab in preferences
2. Find `Wiki Search` in the extensions list
3. Change the `Global keyword` setting to whatever you like it to be
4. Click `Save`

Similarly, if you want to add more wikis (or edit/remove existing ones), it's also possible there. 
Wikipedia and the Witcher Fandom are example URLs, but you can change them to whatever wiki you want as long as it exposes MediaWiki API (e.g. all fandom sites). Look [here](https://github.com/zakuciael/ulauncher-wiki-search#usage) for the instructions on how to do this.

> Bare in mind that I can't ensure 100% functionality on all sites since there could be different versions of the MediaWiki installed, API access points, and many other variables. But you can always submit an issue describing the problem with a particular site, and I will look into it.
